# Generated by Django 5.2.17 on 2026-09-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BucketConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('provider', models.CharField(choices=[('aws_s3', 'AWS S3'), ('cloudflare_r2', 'Cloudflare R2')], default='cloudflare_r2', max_length=20, verbose_name='provedor')),
                ('endpoint_url', models.URLField(verbose_name='URL do endpoint')),
                ('bucket_name', models.CharField(max_length=255, verbose_name='nome do bucket')),
                ('access_key_id', models.CharField(max_length=255, verbose_name='access key')),
                ('secret_access_key', models.CharField(max_length=255, verbose_name='secret key')),
                ('region_name', models.CharField(blank=True, default='auto', max_length=100, verbose_name='região')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuração de bucket',
                'verbose_name_plural': 'configurações de bucket',
                'ordering': ['name'],
            },
        ),
    ]
