# Generated by Django 5.2.17 on 2026-09-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketconfig',
            name='public_base_url',
            field=models.URLField(blank=True, help_text='Ex: https://pub-xxxxx.r2.dev — usada para URLs públicas de arquivos', verbose_name='URL pública'),
        ),
    ]
