# Generated by Django 5.2.17 on 2026-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0002_bucketconfig_public_base_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucketconfig',
            name='music_root_prefix',
            field=models.CharField(default='jukebox/Musicas/', help_text='Caminho no bucket onde ficam as músicas. Ex: jukebox/Musicas/', max_length=1024, verbose_name='pasta raiz das músicas'),
        ),
    ]
