# Generated by Django 5.2.17 on 2026-09-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_jukebox', models.CharField(max_length=150, verbose_name='nome da jukebox')),
                ('usuario', models.CharField(max_length=150, unique=True, verbose_name='usuário')),
                ('senha', models.CharField(max_length=128, verbose_name='senha')),
                ('api_token', models.CharField(blank=True, max_length=64, unique=True, verbose_name='token da máquina')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='último acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'máquina',
                'verbose_name_plural': 'máquinas',
                'ordering': ['nome_jukebox'],
            },
        ),
    ]
