# Generated by Django 5.2.17 on 2026-09-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor (R$)')),
                ('origem', models.CharField(choices=[('moeda', 'Moeda'), ('nota', 'Nota'), ('pix', 'Pix'), ('credito', 'Crédito'), ('outro', 'Outro')], default='moeda', max_length=20, verbose_name='origem')),
                ('observacao', models.CharField(blank=True, max_length=255, verbose_name='observação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='inserido em')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='maquinas.maquina', verbose_name='máquina')),
            ],
            options={
                'verbose_name': 'crédito inserido',
                'verbose_name_plural': 'créditos inseridos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicaTocada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica_key', models.CharField(db_index=True, max_length=1024, verbose_name='chave da música')),
                ('musica_nome', models.CharField(max_length=512, verbose_name='nome do arquivo')),
                ('titulo', models.CharField(blank=True, max_length=512, verbose_name='título')),
                ('pasta', models.CharField(blank=True, max_length=1024, verbose_name='pasta')),
                ('media_type', models.CharField(default='audio', max_length=16, verbose_name='tipo')),
                ('media_url', models.CharField(blank=True, max_length=2048, verbose_name='URL')),
                ('cover_url', models.CharField(blank=True, max_length=2048, verbose_name='capa')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional — se a escolha gerou cobrança específica.', max_digits=10, null=True, verbose_name='valor cobrado (R$)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='escolhida em')),
                ('maquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tocadas', to='maquinas.maquina', verbose_name='máquina')),
            ],
            options={
                'verbose_name': 'música tocada',
                'verbose_name_plural': 'músicas tocadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='credito',
            index=models.Index(fields=['maquina', 'created_at'], name='maquinas_cred_maq_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='musicatocada',
            index=models.Index(fields=['maquina', 'created_at'], name='maquinas_toc_maq_dt_idx'),
        ),
        migrations.AddIndex(
            model_name='musicatocada',
            index=models.Index(fields=['musica_key'], name='maquinas_toc_key_idx'),
        ),
    ]
