# Generated by Django 5.2.17 on 2026-09-03 19:00

from django.db import migrations, models

import maquinas.teclas


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_credito_musicatocada'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='teclas',
            field=models.JSONField(
                blank=True,
                default=maquinas.teclas.default_teclas,
                help_text='Mapa de teclas da jukebox (configurado no admin, enviado ao app).',
                verbose_name='atalhos de teclado',
            ),
        ),
    ]
