# Generated by Django 5.2.17 on 2026-09-01 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buckets', '0002_bucketconfig_public_base_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('artist', models.CharField(blank=True, max_length=255, verbose_name='artista')),
                ('album', models.CharField(blank=True, max_length=255, verbose_name='álbum')),
                ('storage_key', models.CharField(blank=True, max_length=1024, verbose_name='chave no bucket')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='duração (segundos)')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='tamanho do arquivo')),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='tipo do arquivo')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='musicas', to='buckets.bucketconfig', verbose_name='bucket')),
            ],
            options={
                'verbose_name': 'música',
                'verbose_name_plural': 'músicas',
                'ordering': ['-created_at'],
            },
        ),
    ]
