# Generated by Django 5.2.17 on 2026-09-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buckets', '0003_bucketconfig_music_root_prefix'),
        ('musicas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_path', models.CharField(blank=True, max_length=1024, verbose_name='pasta raiz')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='sincronizado em')),
                ('is_syncing', models.BooleanField(default=False, verbose_name='sincronizando')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('folders_count', models.PositiveIntegerField(default=0, verbose_name='pastas')),
                ('files_count', models.PositiveIntegerField(default=0, verbose_name='arquivos')),
                ('images_count', models.PositiveIntegerField(default=0, verbose_name='imagens')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('bucket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogo_musicas', to='buckets.bucketconfig', verbose_name='bucket')),
            ],
            options={
                'verbose_name': 'catálogo da biblioteca',
                'verbose_name_plural': 'catálogos da biblioteca',
            },
        ),
        migrations.CreateModel(
            name='BibliotecaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('file', 'arquivo'), ('folder', 'pasta')], db_index=True, max_length=16, verbose_name='tipo')),
                ('key', models.CharField(max_length=1024, verbose_name='chave')),
                ('name', models.CharField(max_length=512, verbose_name='nome')),
                ('title', models.CharField(blank=True, max_length=512, verbose_name='título')),
                ('folder_path', models.CharField(db_index=True, max_length=1024, verbose_name='pasta')),
                ('extension', models.CharField(blank=True, max_length=16, verbose_name='extensão')),
                ('media_type', models.CharField(db_index=True, max_length=16, verbose_name='tipo de mídia')),
                ('size', models.PositiveBigIntegerField(default=0, verbose_name='tamanho')),
                ('last_modified', models.CharField(blank=True, max_length=64, verbose_name='modificado em')),
                ('media_url', models.CharField(blank=True, max_length=2048, verbose_name='URL pública')),
                ('bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biblioteca_itens', to='buckets.bucketconfig', verbose_name='bucket')),
            ],
            options={
                'verbose_name': 'item da biblioteca',
                'verbose_name_plural': 'itens da biblioteca',
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='bibliotecaitem',
            constraint=models.UniqueConstraint(fields=('bucket', 'key'), name='uniq_biblioteca_item_bucket_key'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaitem',
            index=models.Index(fields=['bucket', 'kind', 'folder_path'], name='musicas_biblio_path_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaitem',
            index=models.Index(fields=['bucket', 'media_type'], name='musicas_biblio_media_idx'),
        ),
        migrations.AddIndex(
            model_name='bibliotecaitem',
            index=models.Index(fields=['name'], name='musicas_biblio_name_idx'),
        ),
    ]
